[GENERAL]
Enabled: True
Sysfs_Power_Path: /sys/class/power_supply/AC*/online
Autoreload: True

[BATTERY]
Update_Rate_s: 30
PL1_Tdp_W: 10
PL1_Duration_s: 28
PL2_Tdp_W: 15
PL2_Duration_S: 0.02
Trip_Temp_C: 95
cTDP: 1
Disable_BDPROCHOT: False

[AC]
Update_Rate_s: 5
PL1_Tdp_W: 25
PL1_Duration_s: 28
PL2_Tdp_W: 28
PL2_Duration_S: 0.02
Trip_Temp_C: 95
cTDP: 2
Disable_BDPROCHOT: False

[UNDERVOLT.BATTERY]
CORE: -70
GPU: -20
CACHE: -70
UNCORE: 0
ANALOGIO: 0

[UNDERVOLT.AC]
CORE: -70
GPU: -20
CACHE: -70
UNCORE: 0
ANALOGIO: 0
