[ui]
theme = "Solarized"
outline_width = 30
tree_style = "spaced"

[terminal]
color_mode = "auto"
warned_terminal_app = false

[theme]

[keybindings]

[editor]

[images]
enabled = true

[content]
hide_frontmatter = true
hide_latex = true
latex_aggressive = true
