# =============
# === INPUT ===
# =============
input {
    kb_layout = us, latam
    kb_options=grp:win_space_toggle
    follow_mouse = 1
    sensitivity = 0
    scroll_factor = 1

    accel_profile = flat

    touchpad {
      natural_scroll = true
    	disable_while_typing = false
      scroll_factor = 1.5
    }
}

cursor {
  no_hardware_cursors = 2
  hide_on_key_press = true
  min_refresh_rate = 60
  no_break_fs_vrr = 1
}

gesture = 3, horizontal, workspace

gestures {
    workspace_swipe_distance = 240
    workspace_swipe_create_new = false
}

device {
    name = elan06fa:00-04f3:327e-touchpad
    accel_profile = adaptive
}

device {
    name = hid-1bcf:08a0-mouse
    sensitivity = -0.09
}
