# =============
# === Rules ===
# =============

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = floating-on-save
    match:class = xdg-desktop-portal-gtk
    match:title = (.*)([Ss]ave.*)
    float = yes
}

windowrule {
    name = fix-onlyoffice-menu
    match:class = ONLYOFFICE*
    match:xwayland = true
    match:float = true
    border_size = 0
}

windowrule {
    name = floating-class
    match:class = float
    float = yes
}

windowrule {
    name = floating-steam
    match:class = steam
    float = yes
  }

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = disable-blur

    match:class = .*

    no_blur = 1
}

windowrule {
    name = enable-blur-for-alacritty

    match:class = Alacritty

    no_blur = 0
}

windowrule {
    name = cmclient
    match:title = ^(CMCLIENT 1\.8\.9.*)$
    immediate = false
    border_size = 0
}
