# Global
splash = false

# Per monitor
wallpaper {
    monitor = eDP-1
    path = /home/jwd/Pictures/wallpapers/223.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/jwd/Pictures/wallpapers/226.jpg
    fit_mode = cover
}
