# Colors (Emberbox)

[colors.primary]
background = '#1c1b19'
foreground = '#E8D9C3'

[colors.normal]
black   = '#1A1816'
red     = '#E0675E'
green   = '#9EB67C'
yellow  = '#E2B86B'
blue    = '#7A9DBB'
magenta = '#B18AC7'
cyan    = '#7FB4A8'
white   = '#D5C5B1'

[colors.bright]
black   = '#5C544C'
red     = '#F07A6D'
green   = '#B5CC8D'
yellow  = '#F0C978'
blue    = '#93B4D1'
magenta = '#C9A5DD'
cyan    = '#96CCC0'
white   = '#F2E7D6'

[colors.selection]
text = '#1A1816'
background = '#E2B86B'
