[colors.primary]
background = '#171717'
foreground = '#fafafa'

[colors.normal]
black   = '#52525b'
red     = '#f87171'
green   = '#4ade80'
yellow  = '#fbbf24'
blue    = '#60a5fa'
magenta = '#a78bfa'
cyan    = '#22d3ee'
white   = '#d4d4d8'

[colors.bright]
black   = '#71717a'
red     = '#ef4444'
green   = '#22c55e'
yellow  = '#f59e0b'
blue    = '#3b82f6'
magenta = '#8b5cf6'
cyan    = '#06b6d4'
white   = '#fafafa'

# Optional cursor
[colors.cursor]
text   = '#171717'
cursor = '#fafafa'

# Optional selection
[colors.selection]
text       = '#fafafa'
background = '#1e3a8a'

# Optional search
[colors.search.matches]
foreground = '#171717'
background = '#fbbf24'

[colors.search.focused_match]
foreground = '#ffffff'
background = '#3b82f6'
