# Colors (Ashen)

[colors.primary]
background = '#101315'
foreground = '#cacccc'

[colors.normal]
black = '#080a0b'
red = '#565d60'
green = '#9fa5a9'
yellow = '#d9dbdc'
blue = '#798186'
magenta = '#aeaeae'
cyan = '#707070'
white = '#cacccc'

[colors.bright]
black = '#4b4e55'
red = '#de6145'
green = '#4c595f'
yellow = '#c9c2b4'
blue = '#5d6367'
magenta = '#9a9a9a'
cyan = '#707070'
white = '#a5aeb4'

[colors.selection]
text = '#cacccc'
background = '#343d41'
